
- name: Ensure creation of folders
  file:
    path: "{{ item }}"
    state: directory
    # owner: "{{ remote_username }}"
  with_items:
    - "{{ seedbox_data }}/cloudcmd_db"

- name: Downloading docker images
  docker_image:
    name: "{{ item }}"
  with_items:
    - hacdias/filemanager
    - coderaiser/cloudcmd

- name: Create filemanager container
  docker_container:
    name: web_filemanager
    image: hacdias/filemanager
    env:
      VIRTUAL_HOST: "{{ files_subdomain }}mgr.{{ seedbox_hostname }}"
    volumes:
      - "{{ seedbox_data }}/files:/srv"
      - "{{ seedbox_data }}/filemanager_db:/etc/database.db"
    recreate: true
    state: started

- name: Create cloudcmd container
  docker_container:
    name: web_cloudcmd
    image: coderaiser/cloudcmd
    env:
      VIRTUAL_HOST: "{{ files_subdomain }}cmd.{{ seedbox_hostname }}"
      VIRTUAL_PORT: 8000
    volumes:
      - "{{ seedbox_data }}/files:/share"
      - "{{ seedbox_data }}/cloudcmd_db:/root"
    command: --one-panel-mode --no-contact --root /share
    recreate: true
    state: started
