- name: Test if docker installed
  command: docker -v
  register: docker_installed
  ignore_errors: yes

- name: Download docker deb
  get_url:
    url: https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_17.05.0~ce-0~ubuntu-xenial_amd64.deb
    dest: /tmp/docker.deb
  when: docker_installed | failed

- name: Install docker
  apt: deb=/tmp/docker.deb
  when: docker_installed | failed

- name: Delete docker deb
  file: path=/tmp/docker.deb state=absent

- name: Install pip
  apt: name=python-pip state=present

- name: Upgrade pip module
  pip: name=pip state=latest

- name: Install docker pip module
  pip: name=docker state=present
