- name: Ensure creation of folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ seedbox_data }}/rtorrent_db"
    - "{{ seedbox_data }}/files"
    # - "{{ seedbox_data }}/flood-db"

- name: Ensure rights of folders
  file:
    path: "{{ item }}"
    state: touch
    mode: "a+rw"
  with_items:
    - "{{ seedbox_data }}/rtorrent_db"
    - "{{ seedbox_data }}/files"

## Rtorrent + rutorrent container
- name: Create torrents container
  docker_container:
    name: rutorrent
    image: kfei/docktorrent
    dns_servers:
      - 8.8.8.8
    published_ports:
      - 45566:45566/tcp
      - 9527:9527/udp
    interactive: false
    tty: true
    env:
      VIRTUAL_HOST: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
      VIRTUAL_PORT: 80
      # Required to handle authentication on a seedbox level
      AUTH_OFF: all
      LOGS_OFF: yes
    volumes:
      - "{{ seedbox_data }}/rtorrent_db:/rtorrent"
      - "{{ seedbox_data }}/files:/rtorrent/downloads"
    recreate: true
    state: started



## Flood + rtorrent container
# - name: Create rtorrent-flood container
#   docker_container:
#     name: rtorrent-flood
#     image: wonderfall/rtorrent-flood
#     published_ports:
#       - 49184
#       - 127.0.0.1:3000:3000
#     interactive: false
#     tty: true
#     env:
#       VIRTUAL_PORT: 3000
#       VIRTUAL_HOST: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
#       # CONTEXT_PATH: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
#       FLOOD_SECRET: "{{ flood_secret }}"
#     volumes:
#       - "{{ seedbox_data }}/files:/data/"
#       - "{{ seedbox_data }}/flood-db/:/flood-db/"
#     recreate: no
#     state: started
