- name: Ensure creation of folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ seedbox_data }}/torrents"
    # - "{{ seedbox_data }}/flood-db"

## Rtorrent + rutorrent container
- name: Create torrents container
  docker_container:
    name: rutorrent
    image: kfei/docktorrent
    dns_servers:
      - 8.8.8.8
    published_ports:
      - 45566:45566
      - 9527:9527/udp
    interactive: false
    tty: true
    env:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
      # Required to handle authentication on a seedbox level
      AUTH_OFF: all

      # CONTEXT_PATH: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
    volumes:
      - "{{ seedbox_data }}/files:/rtorrent"
    recreate: no
    state: started



## Flood + rtorrent container
# - name: Create rtorrent-flood container
#   docker_container:
#     name: rtorrent-flood
#     image: wonderfall/rtorrent-flood
#     published_ports:
#       - 49184
#       - 127.0.0.1:3000:3000
#     interactive: false
#     tty: true
#     env:
#       VIRTUAL_PORT: 3000
#       VIRTUAL_HOST: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
#       # CONTEXT_PATH: "{{ torrent_subdomain }}.{{ seedbox_hostname }}"
#       FLOOD_SECRET: "{{ flood_secret }}"
#     volumes:
#       - "{{ seedbox_data }}/files:/data/"
#       - "{{ seedbox_data }}/flood-db/:/flood-db/"
#     recreate: no
#     state: started
